# Generated by Django 5.1.2 on 2024-10-18 12:04

import django.db.models.deletion
import questionnaires.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='type',
        ),
        migrations.AddField(
            model_name='answer',
            name='detials',
            field=models.JSONField(default={}, validators=[questionnaires.models.answer_details_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
    ]
